version: '3.1'
services:

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-container-data:/var/lib/postgresql/data
    networks:
      - backend

  dcr-svc:
    image: ghanshyamrawat4/dcr-service:v1.2
    ports: 
      - "8098:8098"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dcr_service
      - FLYWAY_URL=jdbc:postgresql://db:5432/dcr_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend


networks:
  backend:

volumes:
  pg-container-data: